"""Business logic for calculating CO2 emissions from cargo transport.

Formula (tonne-km energy consumption model):
    emissions_kg = efficiency_factor * cargo_weight_t * distance_km * emission_factor
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass
from typing import Final

from app.domain.exceptions import InvalidEmissionInputError, InvalidVehicleTypeError
from app.domain.vehicle_type import VehicleType

logger = logging.getLogger(__name__)

_EMISSIONS_PRECISION_DECIMALS: Final[int] = 4


def _validate_finite_number(field_name: str, value: object) -> None:
    """Reject anything that is not a real, finite number (no bool, NaN, inf, str, None)."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise InvalidEmissionInputError(field_name, value, "debe ser un valor numérico")
    if not math.isfinite(value):
        raise InvalidEmissionInputError(
            field_name, value, "debe ser un número finito (no NaN ni infinito)"
        )


def _validate_strictly_positive(field_name: str, value: object) -> None:
    _validate_finite_number(field_name, value)
    if value <= 0:
        raise InvalidEmissionInputError(field_name, value, "debe ser estrictamente mayor que cero")


def _validate_non_negative(field_name: str, value: object) -> None:
    _validate_finite_number(field_name, value)
    if value < 0:
        raise InvalidEmissionInputError(field_name, value, "no puede ser negativo")


@dataclass(frozen=True, slots=True)
class EmissionCalculationInput:
    """Immutable value object holding a single emissions calculation request.

    Validation runs once in ``__post_init__``. Because the dataclass is
    frozen, a successfully constructed instance is guaranteed to remain
    valid for its entire lifetime — ``calculate_co2_emissions`` can then
    trust it completely instead of re-validating on every call. This holds
    regardless of the caller (API layer, batch script, another service,
    tests), since validation is enforced at construction time, not at the
    HTTP boundary.

    Attributes:
        vehicle_type: the transport vehicle category.
        cargo_weight_tonnes: weight of the transported cargo, in tonnes (t).
        distance_km: distance travelled, in kilometres (km).
        efficiency_factor: energy/fuel consumption per tonne-kilometre
            (e.g. L/(t·km) for Diésel/Híbrido, kWh/(t·km) for Eléctrico).
        emission_factor: kg of CO2 emitted per unit of energy/fuel consumed
            (e.g. kgCO2/L, kgCO2/kWh).

    Raises:
        InvalidVehicleTypeError: if vehicle_type is not a VehicleType member.
        InvalidEmissionInputError: if any numeric field is missing, of the
            wrong type, non-finite (NaN/inf), non-positive where a positive
            value is required, or negative where negative is disallowed.
    """

    vehicle_type: VehicleType
    cargo_weight_tonnes: float
    distance_km: float
    efficiency_factor: float
    emission_factor: float

    def __post_init__(self) -> None:
        if not isinstance(self.vehicle_type, VehicleType):
            raise InvalidVehicleTypeError(self.vehicle_type)
        _validate_strictly_positive("cargo_weight_tonnes", self.cargo_weight_tonnes)
        _validate_strictly_positive("distance_km", self.distance_km)
        _validate_strictly_positive("efficiency_factor", self.efficiency_factor)
        _validate_non_negative("emission_factor", self.emission_factor)


def calculate_co2_emissions(calculation_input: EmissionCalculationInput) -> float:
    """Calculate the CO2 emissions (kg) generated by a cargo transport trip.

    Applies the tonne-km energy consumption model:

        emissions_kg = efficiency_factor * cargo_weight_t * distance_km * emission_factor

    ``calculation_input`` is an ``EmissionCalculationInput``, whose
    constructor already enforces every domain invariant (positive weight
    and distance, positive efficiency, non-negative emission factor, a
    supported vehicle type). This function therefore performs the
    calculation only — it does not duplicate validation already guaranteed
    by the value object's frozen, validated construction.

    Args:
        calculation_input: a validated, immutable calculation input.

    Returns:
        Total CO2 emissions in kilograms, rounded to a fixed precision to
        avoid exposing floating-point noise to callers.
    """
    raw_emissions_kg = (
        calculation_input.efficiency_factor
        * calculation_input.cargo_weight_tonnes
        * calculation_input.distance_km
        * calculation_input.emission_factor
    )
    emissions_kg = round(raw_emissions_kg, _EMISSIONS_PRECISION_DECIMALS)

    logger.info(
        "co2_emissions_calculated",
        extra={
            "vehicle_type": calculation_input.vehicle_type.value,
            "cargo_weight_tonnes": calculation_input.cargo_weight_tonnes,
            "distance_km": calculation_input.distance_km,
            "emissions_kg": emissions_kg,
        },
    )

    return emissions_kg
